name: Build and Test

on:
  pull_request:

jobs:
  setup:
    uses: The-Poolz/solidity-workflows/.github/workflows/setup.yml@v0.4.0

  test:
    needs: setup
    uses: The-Poolz/solidity-workflows/.github/workflows/gas-test.yml@v0.4.0