name: Build and Test

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    setup:
        uses: The-Poolz/solidity-workflows/.github/workflows/setup.yml@v0.6.0

    test:
        needs: setup
        uses: The-Poolz/solidity-workflows/.github/workflows/gas-test.yml@v0.6.0
